name: password
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+100
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  fzregex: ^2.0.0
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  injectable_generator: ^2.6.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/google_fonts/Magra-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Magra-Bold.ttf
          weight: 500
