name: password
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+100
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  equatable: ^2.0.5
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  fzregex: ^2.0.0
  get_it: ^7.7.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.19.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/google_fonts/Magra-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Magra-Bold.ttf
          weight: 500
