name: password
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  chopper: ^7.2.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.6.0
  fzregex: ^2.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  injectable: ^2.3.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.1.0
  meta: ^1.10.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.8
  chopper_generator: ^7.2.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  injectable_generator: ^2.5.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/google_fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/google_fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/NotoSans-Bold.ttf
          weight: 700
