import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:password/config/theme/colors.dart' as app;

final typography = TextTheme(
  displayLarge: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 57,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: -0.25,
    height: 1.12,
  ),
  displayMedium: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 45,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.16,
  ),
  displaySmall: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 36,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.12,
  ),
  headlineLarge: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 32,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.25,
  ),
  headlineMedium: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 28,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.29,
  ),
  headlineSmall: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.33,
  ),
  titleLarge: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0,
    height: 1.27,
  ),
  titleMedium: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: app.Colors.textColor,
    letterSpacing: 0.15,
    height: 1.50,
  ),
  titleSmall: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    color: app.Colors.textColor,
    letterSpacing: 0.10,
    height: 1.43,
  ),
  bodyLarge: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0.50,
    height: 1.50,
  ),
  bodyMedium: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0.25,
    height: 1.43,
  ),
  bodySmall: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    color: app.Colors.textColor,
    letterSpacing: 0.40,
    height: 1.33,
  ),
  labelLarge: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    color: app.Colors.textColor,
    letterSpacing: 0.10,
    height: 1.43,
  ),
  labelMedium: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    color: app.Colors.textColor,
    letterSpacing: 0.50,
    height: 1.33,
  ),
  labelSmall: GoogleFonts.notoSans(
    fontStyle: FontStyle.normal,
    fontSize: 11,
    fontWeight: FontWeight.w500,
    color: app.Colors.textColor,
    letterSpacing: 0.50,
    height: 1.45,
  ),
);
