// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_4RupYs16MR0D_y5BKQUFP7aaIgj1gw',
    appId: '1:462283551772:web:4b33d6b71e684f5c5c1bd9',
    messagingSenderId: '462283551772',
    projectId: 'password-app-3b9ea',
    authDomain: 'password-app-3b9ea.firebaseapp.com',
    storageBucket: 'password-app-3b9ea.appspot.com',
    measurementId: 'G-L6B84M3PLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyzlr1aCmkaca7I7EqLDtC2nEF37XGpY',
    appId: '1:462283551772:android:3a1f43492e1f7c4f5c1bd9',
    messagingSenderId: '462283551772',
    projectId: 'password-app-3b9ea',
    storageBucket: 'password-app-3b9ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BY7yTI1_CpvhXzSpLmG7u7hGWqAEkBc',
    appId: '1:462283551772:ios:0ada5b4e30e40d415c1bd9',
    messagingSenderId: '462283551772',
    projectId: 'password-app-3b9ea',
    storageBucket: 'password-app-3b9ea.appspot.com',
    iosBundleId: 'password.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9BY7yTI1_CpvhXzSpLmG7u7hGWqAEkBc',
    appId: '1:462283551772:ios:64ffa109c9c294365c1bd9',
    messagingSenderId: '462283551772',
    projectId: 'password-app-3b9ea',
    storageBucket: 'password-app-3b9ea.appspot.com',
    iosBundleId: 'com.password.RunnerTests',
  );
}
